name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generate snake properly with full grid control
      - uses: Platane/snk@v3
        with:
          github_user_name: FAHAD-FAROOQ-96
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&padding=10&empty_color=%230d1117
